name: vsmart_app
description: A smart academic management system app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  intl: ^0.18.1
  file_picker: ^8.0.0
  percent_indicator: ^4.2.3
  fl_chart: ^0.66.2
  shared_preferences: ^2.2.2
  open_filex: ^4.3.2
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.6
  excel: ^2.1.0
  file_saver: ^0.2.8
  media_store_plus: ^0.1.2
  http: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_marksheet.pdf